name: Close Dataset Issues

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Load Issue Mapping
        id: load-mapping
        run: |
          if [ -f .github/issue_mapping.yaml ]; then
            echo "ISSUE_MAPPING=$(cat .github/issue_mapping.yaml)" >> $GITHUB_ENV
          else
            echo "No issue mapping file found."
            exit 1
          fi

      - name: Identify Datasets in Pull Request
        id: find-datasets
        run: |
          MODIFIED_FILES=$(git diff --name-only main HEAD)
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
          CLOSED_IDS=$(echo "$MODIFIED_FILES" | grep -E '^[^/]+\.yaml$' | sed 's|\.yaml$||')
          echo "CLOSED_IDS=$CLOSED_IDS" >> $GITHUB_ENV

      - name: Close Issues for Datasets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_MAPPING: ${{ env.ISSUE_MAPPING }}
          CLOSED_IDS: ${{ env.CLOSED_IDS }}
        run: |
          echo "Closing issues for IDs: $CLOSED_IDS"
          for ID in $CLOSED_IDS; do
            ISSUE_NUMBER=$(echo "$ISSUE_MAPPING" | grep "$ID:" | cut -d ":" -f 2 | xargs)
            if [ -n "$ISSUE_NUMBER" ]; then
              curl -X PATCH \
                   -H "Authorization: token $GITHUB_TOKEN" \
                   -H "Accept: application/vnd.github+json" \
                   "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER" \
                   -d '{"state": "closed"}'
              echo "Closed issue #$ISSUE_NUMBER for dataset $ID."
            else
              echo "No issue found for dataset $ID."
            fi
          done
